[functions.update_driver_location]
enabled = true
verify_jwt = false
import_map = "./functions/update_driver_location/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update_driver_location/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update_driver_location/*.html" ]



